### ISSUE TITLE
APK Bereitstellen

### ISSUE THREAD

**Issue by djuelg** [djuelg/Neuronizer#36]
- link zu Store in Readme
- https://android-arsenal.com/ in Readme
- verlinken lassen von verwendeten libs

**Comment by IzzySoft** [comment]
APK im Repo wäre noch eine tolle Idee (am besten in `releases/`). Dann könnte ich sie auch in [mein F-Droid kompatibles Repo](https://apt.izzysoft.de/fdroid) mit aufnehmen. Das offizielle F-Droid Repo wäre natürlich noch besser :wink:

**Comment by djuelg** [comment]
@IzzySoft Habe von F-Droid noch nichts gehört gehabt, klingt aber nach einer coolen Sache. Ich werde mich demnächst darum kümmern.

**Comment by IzzySoft** [comment]
Die "Aufnahmeprozedur" dort benötigt etwas mehr Zeit. Vom "Tag der Antragstellung" bis zur Veröffentlichung gehen schon einmal ein paar Wochen ins Land – insbesondere, wenn Komplikationen auftauchen. Mein Repo dient da häufig der "Überbrückung", auch Updates erscheinen bei mir schneller (idR binnen 24h nach Bereitstellung der APK). Während bei mir die Signatur des Entwicklers auf dem APK bleibt (Cross-Updates mit Playstore etc. sind also möglich), signiert F-Droid selbst, erstellt auch die APK neu aus den Quellen.

Nur als kleinen Hintergrund also. Wenn Du Fragen hast: Ich habe dieses Issue hier "in Verfolgung".

**Comment by djuelg** [comment]
@IzzySoft Hey, ich würde mich zumindest mal an den Upload des APK machen. Was genau muss ich denn hochladen? Einfach ein unsigniertes APK aus apk/debug? Reicht es als github release oder muss das APK auch im Repository liegen?

**Comment by IzzySoft** [comment]
@djuelg es muss ein signiertes APK sein (sonst wird es von fdroidserver nicht akzeptiert). Besser auch "release" als "debug" (sonst gibt es so ein hässliches "AntiFeature:ApplicationDebuggable"). Github `releases/` genügt für mein Repo komplett (ist auch von mir bevorzugt).

**Comment by IzzySoft** [comment]
@djuelg Habe ich Dich jetzt verschreckt? Oder das Detail für das "wie uploaden" vergessen: siehe [Creating Releases](https://help.github.com/articles/creating-releases/) in der Github-Hilfe :wink:

**Comment by djuelg** [comment]
Nein nein, zur Zeit muss ich mich leider um andere Dinge kümmern. Danke für die Infos!

**Comment by djuelg** [comment]
Hey @IzzySoft das APK ist jetzt hochgeladen :)
[https://github.com/djuelg/Neuronizer/releases/tag/1.3.3](https://github.com/djuelg/Neuronizer/releases/tag/1.3.3)

**Comment by IzzySoft** [comment]
Super, Danke! Jetzt auch [in meinem Repo zu finden](https://apt.izzysoft.de/fdroid/index/apk/de.djuelg.neuronizer). Wärst Du offen dafür, Deine App in das offizielle F-Droid Repo zu bekommen? Ich sehe auf Anhieb nichts, was dem entgegenstünde. Helfe Dir gern dabei, es "hinein zu bekommen".
