### ISSUE TITLE
Error in classe SillySavedRepositoryPassword

### ISSUE THREAD

**Issue by neguives** [djuelg/Neuronizer#70]
![neuronize](https://user-images.githubusercontent.com/31361409/50369717-f839c880-0580-11e9-874d-94008eeceb49.PNG)

Good night! First of all, I would like to commend you for the development of this App- Simply Fantastic! The problem is that I can not perform a build, an error appears in the import of this class: SillySavedRepositoryPassword. What should be done ?

**Comment by djuelg** [comment]
Sorry for the late reply! You have to create a class like the following:
The only thing missing here is there byte[] variable called password which you have to generate yourself :)

```
class SillySavedRepositoryPassword {

    static byte[] letMeReadImLegit(){
        return password;
    }
}
```
